library(tidyverse)
library(Seurat)
library(patchwork)

setwd('/Users/juanjovel/jj/data_analysis/hollySparks/dataIntegration_wSeurat/human_and_mouse')
dir <- getwd()

# Here we will use a dataset generated by 10X on PBMCs samples containing 2,700 cells

# Read10X loads CellRanger results in text format, which were originally produced by Cell Ranger
# which are in text format and comprises 3 files: barcodes.tsv, genes.tsv,matrix.mtx
# Newer format HDF5 is handled by function Read10X_h5()
mouse.data <- Read10X(data.dir = dir)

# Create a Seurat object to store data from Cell Ranger and results generated along
# pipeline processing
mouse <- CreateSeuratObject(counts = mouse.data, project = "mouse", min.cells = 3, min.features = 200)




# Step 1: Generate Random Gene Names
set.seed(123)  # Set seed for reproducibility
random_gene_names <- paste0("Gene", 1:32285)
write.table(random_gene_names, "new_genes.tsv", quote = F, row.names = F)
